CREATE TABLE tb_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caption TEXT,
    image_url VARCHAR(500),
    video_url VARCHAR(500),
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES tb_users(id) ON DELETE CASCADE
);